PROMPT === Switching to PDB &1 ===
ALTER SESSION SET CONTAINER=&1;
SHOW CON_NAME;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'OGGADMIN';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER oggadmin IDENTIFIED BY oggpass';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION, RESOURCE, CONNECT TO oggadmin';
        EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO oggadmin';
        EXECUTE IMMEDIATE 'GRANT FLASHBACK ANY TABLE TO oggadmin';
        EXECUTE IMMEDIATE 'GRANT SELECT ANY TRANSACTION TO oggadmin';
        EXECUTE IMMEDIATE 'GRANT ALTER ANY TABLE TO oggadmin';
        EXECUTE IMMEDIATE 'GRANT ALTER SYSTEM TO oggadmin';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_FLASHBACK TO oggadmin';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_CAPTURE_ADM TO oggadmin';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_APPLY_ADM TO oggadmin';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_STREAMS_ADM TO oggadmin';
        EXECUTE IMMEDIATE 'GRANT LOGMINING TO oggadmin';
        DBMS_GOLDENGATE_AUTH.GRANT_ADMIN_PRIVILEGE('OGGADMIN');
    END IF;
END;
/

-- Verify
SELECT username, account_status, common FROM dba_users WHERE username='OGGADMIN';

EXIT;