PROMPT === Switching to PDB &1 ===
ALTER SESSION SET CONTAINER=&1;
SHOW CON_NAME;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = UPPER('&2');

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER &2 IDENTIFIED BY &3';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION, RESOURCE, CONNECT TO &2';
        EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO &2';
        EXECUTE IMMEDIATE 'GRANT FLASHBACK ANY TABLE TO &2';
        EXECUTE IMMEDIATE 'GRANT SELECT ANY TRANSACTION TO &2';
        EXECUTE IMMEDIATE 'GRANT ALTER ANY TABLE TO &2';
        EXECUTE IMMEDIATE 'GRANT ALTER SYSTEM TO &2';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_FLASHBACK TO &2';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_CAPTURE_ADM TO &2';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_APPLY_ADM TO &2';
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_STREAMS_ADM TO &2';
        EXECUTE IMMEDIATE 'GRANT LOGMINING TO &2';
        DBMS_GOLDENGATE_AUTH.GRANT_ADMIN_PRIVILEGE('&2');
    END IF;
END;
/

-- Verify
SELECT username, account_status, common FROM dba_users WHERE username=UPPER('&2');

EXIT;