PROMPT === Switching to PDB &1 ===
ALTER SESSION SET CONTAINER=&1;
SHOW CON_NAME;

CREATE USER oggadmin IDENTIFIED BY oggpass;
GRANT CREATE SESSION, RESOURCE, CONNECT TO oggadmin;
GRANT SELECT ANY DICTIONARY TO oggadmin;
GRANT FLASHBACK ANY TABLE TO oggadmin;
GRANT SELECT ANY TRANSACTION TO oggadmin;
GRANT ALTER ANY TABLE TO oggadmin;
GRANT ALTER SYSTEM TO oggadmin;
GRANT EXECUTE ON DBMS_FLASHBACK TO oggadmin;
GRANT EXECUTE ON DBMS_CAPTURE_ADM TO oggadmin;
GRANT EXECUTE ON DBMS_APPLY_ADM TO oggadmin;
GRANT EXECUTE ON DBMS_STREAMS_ADM TO oggadmin;
GRANT LOGMINING TO oggadmin;