WHENEVER SQLERROR EXIT FAILURE;

-- Enabling FORCE LOGGING in CDB...
ALTER DATABASE FORCE LOGGING;

PROMPT Checking FORCE LOGGING...
SELECT CASE FORCE_LOGGING WHEN 'YES' THEN 1 ELSE TO_NUMBER(NULL) END AS FORCE_LOGGING_ENABLED
FROM V$DATABASE;

PROMPT Switching to PDB $src_PDB...
ALTER SESSION SET CONTAINER=$src_PDB;

PROMPT Enabling Supplemental Log Data...
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

PROMPT Checking Supplemental Log Data...
SELECT CASE SUPPLEMENTAL_LOG_DATA_MIN WHEN 'YES' THEN 1 ELSE TO_NUMBER(NULL) END AS SUP_LOG_ENABLED
FROM V$DATABASE;